### ISSUE TITLE
Question for code

### ISSUE THREAD

**Issue by hbzhang** [xupei0610/nvidia-end-to-end-self-driving-cars#2]
In model.py, is this right? It is FC layer, right? But why it says conv_layer

  # fc layers
    fc1,   w6, b6 = conv_layer("fc1", dp,    64, 1164, [1, 18], 1, padding="VALID", trainable=trainable, with_bn=True)    # 1164@1x1
    fc2,   w7, b7 = conv_layer("fc2", fc1, 1164,  100, 1, 1, padding="VALID", trainable=trainable, with_bn=True)          # 100@1x1
    fc3,   w8, b8 = conv_layer("fc3", fc2,  100,   50, 1, 1, padding="VALID", trainable=trainable, with_bn=True)          # 50@1x1
    fc4,   w9, b9 = conv_layer("fc4", fc3,   50,   10, 1, 1, padding="VALID", trainable=trainable, with_bn=True)          # 10@1x1
    fc5, w10, b10 = conv_layer("fc5", fc4,   10,    1, 1, 1, padding="VALID",
                               with_elu=False, with_bn=False, trainable=trainable)                           # 1@1x1

**Comment by xupei0610** [comment]
Sorry to reply so late.
They are FC layers but not so typical. I use 1x1 conv to perform operations similar to FC layers at the channel dimension. The H and W dimensions are fixed as 1x1. So, you can simply ignore them at all.
